export * from './slice'
export type { OrderAdditive } from './types/OrderAdditive.type'
export type { Additive } from './types/Additive.type'
export type { Service } from './types/Service.type'
export type { Order } from './types/Order.type'
export { countPrice } from './utils/countPrice'